name: tenseikun_apps
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  audioplayers: ^6.5.1
  flutter:
    sdk: flutter
  flutter_timezone: ^4.1.1
  font_awesome_flutter: ^10.9.1
  home_widget: ^0.9.0
  http: ^1.6.0
  intl: ^0.20.2
  math_expressions: ^2.6.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/paper.png
    - assets/images/rock.png
    - assets/images/scissor.png
    - assets/images/placeholder_image.jpg
    - assets/sounds/player1_tapSound.mp3
    - assets/sounds/player2_tapSound.mp3
    - assets/sounds/winnerAnnouncement.mp3
